language: node_js
node_js:
  - "8"

after_success:
  - docker login $REGISTRY_URL -u $REGISTRY_USER -p $REGISTRY_PASS

  - export APP=sewas/simple-express-server
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  - docker build -t $REGISTRY_URL/$APP:$TAG .
  - docker push $REGISTRY_URL/$APP:$TAG